"""empty message

Revision ID: e6bb4f909e31
Revises: 6db9b3f921a6
Create Date: 2024-12-14 18:59:47.868019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bb4f909e31'
down_revision = '6db9b3f921a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('publisher', sa.String(length=50), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('ISBN', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
